<a href="https://colab.research.google.com/github/sheekhaa/AI-worksheets/blob/main/worksheet1_basanti.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
# 5CS037: Concepts and Technologies of AI
#Name: Basanti Kandel
#Level: 5
#Group: L5CG10
#Student ID:2510348
```



In [52]:
# Problem - 1: Array Creation
#1. Initialize an empty array with size 2X2.
import numpy  as np
a = np.empty ((2, 2))
a


array([[2.5e-323, 1.5e-323],
       [9.9e-324, 4.9e-324]])

In [53]:
# 2. Initialize an all one array with size 4X2.
a = np.ones((4, 2))
a


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
# Return a new array of given shape and type, filled with fill value.{Hint: np.full}
a = np.full((3, 4), 9)
a

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [55]:
#Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
a = ([1, 2, 3], [4, 5, 6])
b = np.zeros_like(a)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [56]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
b = np.ones_like(a)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
a = np.array(new_list)
a

array([1, 2, 3, 4])

In [58]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing
#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
a = np.arange(10,50)
a


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [59]:
#Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
#4. Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
a = np.random.random(30)
b = a.mean()
b

np.float64(0.46815030725322637)

In [62]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.
a = np.random.random((10, 10))
b = a.min()
c = a.max()
a
b
c


np.float64(0.9943935693527926)

In [63]:
#6. Create a zero array of size 10 and replace 5th element with 1.
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [64]:
#7. Reverse an array arr = [1,2,0,0,4,0].
a = np.array([1,2,0,0,4,0])
b = a[::-1]
b

array([0, 4, 0, 0, 2, 1])

In [65]:
#8. Create a 2d array with 1 on border and 0 inside.
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [67]:
#Problem - 3: Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10]);
w = np.array([11,12]);


In [68]:
#1. Add the two array.
x+y

array([[ 6,  8],
       [10, 13]])

In [69]:
#2. Subtract the two array.
x-y

array([[-4, -4],
       [-4, -3]])

In [70]:
# 3. Multiply the array with any integers of your choice.
x*2

array([[ 2,  4],
       [ 6, 10]])

In [71]:
# 4. Find the square of each element of the array.
x**2

array([[ 1,  4],
       [ 9, 25]])

In [72]:
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
np.dot(v,w)
np.dot(x,v)
np.dot(x,y)

array([[19, 22],
       [50, 58]])

In [73]:
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
np.vstack((x,y))
np.column_stack((v, w))

array([[ 9, 11],
       [10, 12]])

In [74]:
np.vstack((x,v))

array([[ 1,  2],
       [ 3,  5],
       [ 9, 10]])

 x is a 2×2 matrix and v is a 1D vector. Their shapes do not match, so they cannot be concatenated.

In [75]:
# Problem - 4: Matrix Operations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);


In [76]:
# 1. Prove A.A−1 = I.
Ai = np.linalg.inv(A)
Ai

array([[-2.  ,  1.  ],
       [ 1.75, -0.75]])

In [77]:
#2. Prove AB ̸= BA.
A.dot(B)
B.dot(A)

array([[36, 44],
       [13, 16]])

In [78]:
#3. Prove (AB) = BTAT.
np.transpose(A.dot(B))
np.dot(np.transpose(B), np.transpose(A))

array([[23, 51],
       [13, 29]])

In [79]:
# • Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
# • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
# of Numpy}
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

x = np.linalg.inv(A).dot(B)
x


array([ 2.,  1., -2.])

In [80]:
#4.2 Experiment: How Fast is Numpy
# 1. Element-wise Addition (Python vs Numpy)
import numpy as np
import time
# Python
a = list(range(1000000))
b = list(range(1000000))

start = time.time()
c = [a[i] + b[i] for i in range(1000000)]
print("Python Time:", time.time() - start)

# Numpy
a_np = np.arange(1000000)
b_np = np.arange(1000000)

start = time.time()
c_np = a_np + b_np
print("Numpy Time:", time.time() - start)


Python Time: 0.1003875732421875
Numpy Time: 0.0021309852600097656


In [81]:
#2. Element-wise Multiplication
# Python
start = time.time()
c = [a[i] * b[i] for i in range(1000000)]
print("Python Time:", time.time() - start)

# Numpy
start = time.time()
c_np = a_np * b_np
print("Numpy Time:", time.time() - start)


Python Time: 0.1296215057373047
Numpy Time: 0.0026445388793945312


In [82]:
#3. Dot Product
# Python
start = time.time()
dot_py = sum(a[i] * b[i] for i in range(1000000))
print("Python Time:", time.time() - start)

# Numpy
start = time.time()
dot_np = np.dot(a_np, b_np)
print("Numpy Time:", time.time() - start)


Python Time: 0.11125326156616211
Numpy Time: 0.0018146038055419922


In [84]:
# 4. Matrix Multiplication
# Python
A = [[i for i in range(1000)] for j in range(1000)]
B = [[i for i in range(1000)] for j in range(1000)]

start = time.time()
C = [[sum(A[i][k] * B[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
print("Python Time:", time.time() - start)

# Numpy
A_np = np.arange(1000000).reshape(1000,1000)
B_np = np.arange(1000000).reshape(1000,1000)

start = time.time()
C_np = A_np.dot(B_np)
print("Numpy Time:", time.time() - start)



Python Time: 191.32356142997742
Numpy Time: 1.249600887298584
